CREATE TABLE `Folder` (
	`FolderId` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	`FolderPath` VARCHAR(2000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`FolderName` VARCHAR(1000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`BookName` VARCHAR(2000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`Url` VARCHAR(2000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`RateCount` INT(11) NULL DEFAULT NULL,
	`Rate` DOUBLE NULL DEFAULT NULL,
	`MyRate` DOUBLE NULL DEFAULT NULL,
	`Author` VARCHAR(1000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`PublicationDateText` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`PublicationDate` DATE NULL DEFAULT NULL,
	`Category` VARCHAR(1000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`FolderExists` BIT(1) NULL DEFAULT NULL,
	`UrlUpdated` DATETIME NULL DEFAULT NULL,
	`FolderUpdated` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`FolderId`) USING BTREE
) 

