CREATE TABLE `Folder` (
	`FolderId` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	`FolderPath` VARCHAR(2000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`FolderName` VARCHAR(1000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`BookName` VARCHAR(2000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`Url` VARCHAR(2000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`RateCount` INT(11) NULL DEFAULT NULL,
	`Rate` DOUBLE NULL DEFAULT NULL,
	`MyRate` DOUBLE NULL DEFAULT NULL,
	`Author` VARCHAR(1000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`PublicationDateText` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`PublicationDate` DATE NULL DEFAULT NULL,
	`Category` VARCHAR(1000) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`FolderExists` BIT(1) NULL DEFAULT NULL,
	`UrlUpdated` DATETIME NULL DEFAULT NULL,
	`FolderUpdated` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`FolderId`) USING BTREE,
	KEY `IX_Folder_FolderPath` (`FolderPath`(191)),
	KEY `IX_Folder_FolderName` (`FolderName`(191))
);

CREATE TABLE `AppUser` (
  `UserId` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NOT NULL,
  `DateCreated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastLoginDate` DATETIME NULL DEFAULT NULL,
  `LastFolderId` INT(10) UNSIGNED,
  `LastTimeSeconds` INT(10) UNSIGNED,
  `LastFileUrl` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`) USING BTREE,
  UNIQUE KEY `UX_AppUser_Email` (`Email`)
);

CREATE TABLE `UserLogin` (
	`UserLoginId` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	`UserId` INT(10) UNSIGNED ZEROFILL NOT NULL,
	`LoginDate` DATETIME NOT NULL,
	`IpAddress` VARCHAR(200) NOT NULL,
	PRIMARY KEY (`UserLoginId`) USING BTREE,
	KEY `IX_UserLogin_UserId_LoginDate` (`UserId`, `LoginDate`) USING BTREE,
	CONSTRAINT `FK_UserLogin_AppUser` FOREIGN KEY (`UserId`) REFERENCES `AppUser`(`UserId`) ON DELETE CASCADE
);

CREATE TABLE `UserFolder` (
	`UserId` INT(10) UNSIGNED ZEROFILL NOT NULL,
	`FolderId` INT(10) UNSIGNED ZEROFILL NOT NULL,	
	`Rating` DOUBLE NULL DEFAULT NULL,
	`IsFave` BIT(1) NOT NULL DEFAULT b'0',
	`LastTimeSeconds` INT(10) UNSIGNED NULL DEFAULT NULL,
	`LastFileUrl` VARCHAR(2000) NULL DEFAULT NULL,
	`DateRated` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`UserId`, `FolderId`) USING BTREE,
	KEY `IX_UserFolder_UserId_IsFave` (`UserId`, `IsFave`) USING BTREE,
	FOREIGN KEY (`UserId`) REFERENCES `AppUser`(`UserId`) ON DELETE CASCADE,
	FOREIGN KEY (`FolderId`) REFERENCES `Folder`(`FolderId`) ON DELETE CASCADE
);

-- Sign-in tokens ("remember me" for 30 days)
CREATE TABLE `AuthToken` (
	`Selector` CHAR(24) NOT NULL,
	`ValidatorHash` CHAR(64) NOT NULL,
	`UserId` INT(10) UNSIGNED ZEROFILL NOT NULL,
	`Expires` DATETIME NOT NULL,
	`Created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`LastUsed` DATETIME NULL DEFAULT NULL,
	`UserAgent` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`Selector`),
	KEY `IX_AuthToken_UserId` (`UserId`),
	KEY `IX_AuthToken_Expires` (`Expires`),
	CONSTRAINT `FK_AuthToken_AppUser` FOREIGN KEY (`UserId`) REFERENCES `AppUser`(`UserId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=ascii;

-- For an existing database, run Migration.sql instead of this file.
